delete does not fail if 404

diff --git a/.github/actions/delete-runner/action.yml b/.github/actions/delete-runner/action.yml
--- a/.github/actions/delete-runner/action.yml
+++ b/.github/actions/delete-runner/action.yml
@@ -18,9 +18,16 @@ runs:
     - id: delete-runner
       shell: bash
       run: |
-        curl -L --request DELETE \
+        RESPONSE=$(curl -L --request DELETE \
           --url https://api.github.com/repos/${{ github.repository }}/actions/runners/${{ inputs.runner-id }} \
           --header 'Accept: application/vnd.github+json' \
           --header 'Authorization: Bearer ${{ inputs.api-token }}' \
           --header 'X-GitHub-Api-Version: 2022-11-28' \
-          --fail-with-body --silent --show-error
+          --silent --show-error)
+        if [[ $RESPONSE == *"200 OK"* ]]; then
+          echo "found=true" >> $GITHUB_OUTPUT
+        elif [[ $RESPONSE == *"404 Not Found"* ]]; then
+          echo "found=false" >> $GITHUB_OUTPUT
+        else
+          echo "Request failed" && exit 1
+        fi
